name: redpanda-minimal-dev
networks:
  redpanda_network:
    driver: bridge
services:
  redpanda-0:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.2
    command:
      - redpanda
      - start
      - --kafka-addr
      - internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr
      - internal://redpanda-0:9092,external://localhost:19092
      - --pandaproxy-addr
      - internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --rpc-addr
      - 0.0.0.0:33145
      - --node-id
      - '0'
      - --mode dev-container
    networks:
      - redpanda_network
    ports:
      - '19092:19092' # Kafka API for external clients
      - '18082:18082' # HTTP Proxy for external clients
    volumes:
      - redpanda-0:/var/lib/redpanda/data

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: nosdk
      POSTGRES_PASSWORD: nosdk
      POSTGRES_DB: nosdk
    ports:
      - 15432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio-test
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"     # API port
      - "9001:9001"     # Console UI port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

volumes:
  redpanda-0: null
  pgdata: null
  minio_data: null
